### ISSUE TITLE
Show result faster

### ISSUE THREAD

**Issue by ai** [sindresorhus/speed-test#1]
Web UI is faster to use. I can get `ping` right after first donwload bytes. I can view a download speed before it will download all files.

In most time I didn’t interesting in upload speed, but anyway in CLI I need to wait this check before get ping and download results.

**Comment by sindresorhus** [comment]
I personally just start it and come back later, but sure. Sounds useful.

I'm thinking showing the down/up speed in realtime as the result is now, but in yellow to signify it's not the final result.

**Comment by ai** [comment]
Yeap, it will awesome :). SpeedTest.net has too many ads, so you CLI tool is really helpful.

**Comment by daryl** [comment]
+1, thought the exact same thing.

**Comment by bhaveshgohel** [comment]
:+1:

**Comment by mCzolko** [comment]
That would be awesome. Anyway, thank you for this one! :+1:

**Comment by sindresorhus** [comment]
Alright. New version is out. You can upgrade to v1.1.0 by running: `npm i -g speed-test`.
