### ISSUE TITLE
Add --share option - to share the typical speedtest.png

### ISSUE THREAD

**Issue by CodeBrauer** [sindresorhus/speed-test#12]
Would be nice to add an option like `--share` to get a link to share your result:

![4449580908](https://cloud.githubusercontent.com/assets/2059754/9462050/237e63d8-4b13-11e5-895d-49171691a693.png)

Like: https://github.com/sivel/speedtest-cli

**Comment by sindresorhus** [comment]
:+1: A good PR would be merged, but I don't need this myself, so won't come from me.

**Comment by SamVerschueren** [comment]
If someone can convince me this is a useful feature I would have a look to implementing this. But to me personally, this plugin is really just for my own needs. Never feel the need to share my speedtest result.

**Comment by CodeBrauer** [comment]
@SamVerschueren I'm using the share format somtimes because of:
- saving this data (it has all data that I need)
- sharing the result to my ISP/Customer

It was just an idea, mainly a pretty basic text output does the job very well.

**Comment by SamVerschueren** [comment]
Hi @CodeBrauer 

So if the `--verbose` flag is implemented (see https://github.com/sindresorhus/speed-test/issues/6), that would provide you with enough information?

@sindresorhus, wdyt? Do you want this feature to be implemented? I let you decide, it's your module after all ;).

**Comment by CodeBrauer** [comment]
@SamVerschueren - Oh didn't catch that, I should really update my npm packages more often. That's enough for me :+1:

**Comment by sindresorhus** [comment]
`--verbose` flagged was added in https://github.com/sindresorhus/speed-test/pull/21, so I consider this fixed.
