### ISSUE TITLE
Just spins on Ping

### ISSUE THREAD

**Issue by pixmonkey** [sindresorhus/speed-test#13]
Any reason the test would just spin and stick on the Ping?

Not really sure if it is an issue but it is what I am seeing when I run the test in OSX Terminal.

**Comment by sindresorhus** [comment]
Do you happen to be behind a proxy? https://github.com/ddsol/speedtest.net/issues/8

**Comment by pixmonkey** [comment]
No. The only thing close to that would be I am using DHCP on my router.

**Comment by thomasqbrady** [comment]
+1

**Comment by diffsky** [comment]
I'm hanging on ping too. Digging into the guts of the [speed-test module](https://github.com/ddsol/speedtest.net) it was getting stuck here:
https://github.com/ddsol/speedtest.net/blob/master/index.js#L260
In my test:
- `servers.length` was 3760
- `count` was 5 (this value comes from [default options](https://github.com/ddsol/speedtest.net/blob/master/index.js#L412))

The `pingServers` function has a loop using the smallest of the two above values. The `n` variable used in the loop is zero based it was never reaching 5. Initializing as `var n=1` and checking with `<=todo` made things work:
```
for(var n=1;n<=todo;n++)(function(server){
```

**Comment by pixmonkey** [comment]
Yep, that fixed it. Nicely done.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/ddsol/speedtest.net/issues/12.
