### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by kytwb** [sindresorhus/speed-test#16]
Would it be interesting to add proxy support to be able to see a proxy speed?
I'll be down to contribute if people are interested.

**Comment by sindresorhus** [comment]
This needs to be fixed in the underlying lib. See: https://github.com/ddsol/speedtest.net/issues/8

**Comment by herlon214** [comment]
👍

**Comment by shaodahong** [comment]
👍

**Comment by rgaspary** [comment]
👍

**Comment by sindresorhus** [comment]
Fixed by https://github.com/ddsol/speedtest.net/pull/47
