### ISSUE TITLE
Option to show speeds in megabytes rather than megabits

### ISSUE THREAD

**Issue by Calinou** [sindresorhus/speed-test#28]
There could be an option called `--bytes` to show speeds in megabytes rather than megabits.

**Comment by sindresorhus** [comment]
Why?

**Comment by Calinou** [comment]
> Why?

- It will give you a semi-accurate estimate of how fast you can download and upload files
- Speedtest.net and speedtest-cli (Python) do it :)

**Comment by SamVerschueren** [comment]
> It will give you a semi-accurate estimate of how fast you can download and upload files

Mbps do too :)

**Comment by sindresorhus** [comment]
@Calinou I agree. Mbps is mostly just useful as a relative measuring unit. People know approximately how fast 10 Mbps is, but they usually don't know what it actually means.

Pull request welcome :)
