### ISSUE TITLE
No compatible version found: update-notifier@'>=0.6.0 <0.7.0'

### ISSUE THREAD

**Issue by davo** [sindresorhus/speed-test#29]
I tried to install the CLI but the dev dependency "update-notifier" reaches 0.5.0.

I got node v0.12.7 and npm v2.12.1

**Comment by SamVerschueren** [comment]
Can you print screen your exact error? `update-notifier` is not a dev dependency, but a dependency and it should install `0.6.0`.

**Comment by davo** [comment]
davo@pixelbeat:~/Dropbox|⇒  sudo npm install -G speed-test
npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-G" "speed-test"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: update-notifier@'>=0.6.0 <0.7.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8","0.1.9","0.1.10","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2","0.4.0","0.5.0"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'speed-test'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/davo/Dropbox/npm-debug.log

**Comment by sindresorhus** [comment]
This is a problem with npm. Use the [npm issue tracker](https://github.com/npm/npm/issues) for npm support.
