### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by loctauxphilippe** [sindresorhus/speed-test#3]
this is not an issue at all, I just wanted to thank you for this awesome tool! :smiley:

**Comment by sindresorhus** [comment]
Happy to hear you enjoy it. I'm currently working on an update that makes it even better. Stay tuned.

**Comment by loctauxphilippe** [comment]
Good! I'll wait for it :)

**Comment by sindresorhus** [comment]
New version is out. You can upgrade to v1.1.0 by running: `npm i -g speed-test`.

**Comment by Frikki** [comment]
:+1:
