### ISSUE TITLE
Location, location...

### ISSUE THREAD

**Issue by mateatslc** [sindresorhus/speed-test#33]
wherever I run it, tests against `speedo.eltele.no` in Alta, Norway resulting in incorrect measurements.

![screen shot 2016-02-11 at 10 42 50 am](https://cloud.githubusercontent.com/assets/590577/12973431/9b92e564-d0ac-11e5-8d18-79e9653087a9.png)

OSX 10.11.3 / iTerm2 / testing from Hungary

**Comment by SamVerschueren** [comment]
@mateatslc Would you be able to log what `server.distance` holds? https://github.com/sindresorhus/speed-test/blob/master/cli.js#L78

Seems like the `speed-test` API we use might not return a numeric value in your case.

**Comment by sindresorhus** [comment]
// @ddsol

**Comment by mateatslc** [comment]
`server.distance` is `null`
here is the complete `server` object stringified:
```
{
  "bestPing": 165.76601300000002,
  "cc": "NO",
  "country": "Norway",
  "dist": null,
  "distMi": null,
  "id": "3433",
  "lat": "69.9403",
  "lon": "23.3106",
  "name": "Alta",
  "sponsor": "Eltele AS",
  "url": "http://speedo.eltele.no/speedtest/upload.php"
}
```

**Comment by paicha** [comment]
Same issue, testing from China.

**Comment by SamVerschueren** [comment]
@sindresorhus What should be shown if `distance` is `null`? Grayed out `Unknown`?

**Comment by ddsol** [comment]
I'm not understanding how [dist could ever be null](https://github.com/ddsol/speedtest.net/blob/master/index.js#L547). Is this data coming from before that line? Maybe some more `console.log` lines could help here, together with where these lines are.

**Comment by clarkio** [comment]
@mateatslc I think this is related to the issue I was seeing when running this module. I was finding it always defaulting to the Norway server you mentioned as well. Digging deeper I found it to be an issue where the dependency module, [speedtest.net](https://github.com/ddsol/speedtest.net), had a request being blocked by the [speedtest.net service](http://speedtest.net). See more details here: https://github.com/ddsol/speedtest.net/issues/19

This should be fixed now. Reinstall speed-test, making sure it pulls in `speedtest-net@1.2.5` and you should see the expected results.

**Comment by mateatslc** [comment]
@clarkio thanks! works indeed, with `speedtest-net@1.2.5`
@sindresorhus created #34

**Comment by SamVerschueren** [comment]
No need to bump the version. Because of semver, `speedtest-net@1.2.5` will be installed automatically when reinstalling `speed-test`.

**Comment by mateatslc** [comment]
Better safe than sorry ;)

**Comment by clarkio** [comment]
Yes, no need to bump the version. I was referring to the install log when installing `speed-test` to see that it shows `speedtest-net@1.2.5`.
