### ISSUE TITLE
Option to choose network interface

### ISSUE THREAD

**Issue by petersandor** [sindresorhus/speed-test#35]
For example `ping` has the `-I` option:

```
$ ping 8.8.8.8 -I enp5s0
PING 8.8.8.8 (8.8.8.8) from x.x.x.x enp5s0: 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=49 time=40.5 ms

$ ping 8.8.8.8 -I tun0
PING 8.8.8.8 (8.8.8.8) from y.y.y.y tun0: 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=49 time=61.4 ms
```

Is there a similar option to select specific interface for speed test? If not, does anyone else think it would be a good idea to implement?

**Comment by sindresorhus** [comment]
Not something I'm interested in having here. I would recommend trying to get it added to https://github.com/sivel/speedtest-cli, which has more options.
