### ISSUE TITLE
Unable to excute command through command line?

### ISSUE THREAD

**Issue by sas12012** [sindresorhus/speed-test#4]
cscript test.js

**Comment by sindresorhus** [comment]
Please try harder with issue reporting. What doesn't work? Post output here.

**Comment by sas12012** [comment]
Apologies for being vague. I executed cscript test.js within command line of git shell. It returns with "Microsoft Jscript runtime error: Object expected

**Comment by sindresorhus** [comment]
Still vague. Why did you do that? That's not how you run this command-line app. This runs on Node.js, Cscript is not.

**Comment by sas12012** [comment]
Ok thanks.

**Comment by sas12012** [comment]
Executed command through Node.js. Worked great.

**Comment by samccone** [comment]
Jscript FTW
