### ISSUE TITLE
Support for fast.com

### ISSUE THREAD

**Issue by andersfischernielsen** [sindresorhus/speed-test#44]
Netflix's speed test [Fast.com](http://fast.com) gives a more correct result of actual speeds, since it uses Netflix servers for testing, so that your ISP can't throttle the results as they can (and have been known to do) on speedtest.net. 

Support for fast.com in this tool would be awesome. :)

**Comment by sindresorhus** [comment]
I already have a separate tool for that: https://github.com/sindresorhus/fast-cli

**Comment by andersfischernielsen** [comment]
My bad, didn't see that. Awesome!
