### ISSUE TITLE
Support to select server

### ISSUE THREAD

**Issue by plambrechtsen** [sindresorhus/speed-test#45]
Often speedtest doesn't select the fastest speedtest server.
I see under the speedtest-net function there is a serverId, but you can't specify it via command line.

Would be nice if you could specify the server you want to use.

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in such option. I want to keep this as simple as possible. You might want to try https://github.com/sivel/speedtest-cli instead ;)
