### ISSUE TITLE
add support for options in speedtest.net

### ISSUE THREAD

**Issue by nickolasclarke** [sindresorhus/speed-test#46]
https://github.com/ddsol/speedtest.net supports the following options:

* `maxTime` The maximum length of a single test run (upload or download)
* `pingCount` The number of close servers to ping to find the fastest one
* `maxServers` The number of servers to run a download test on. The fastest is used for the upload test and the fastest result is reported at the end.
* `headers` Headers to send to speedtest.net
* `log` (Visual only) Pass a truthy value to allow the run to output results to the console in addition to showing progress, or a function to be used instead of `console.log`.
* `serverId` ID of the server to restrict the tests against.
* `serversUrl` URL to obtain the list of servers available for speed test. (default: http://www.speedtest.net/speedtest-servers-static.php)

these should all be exposed as options (excepting maybe log, which is possibly already used with `--verbose`?) 

For me, this would be especially useful to select and test throughput for VPN vs normal connection on specific servers. I'll poke around and see if I can submit a PR for this.

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in more options. I made this for the most common case and it's done now. I would suggest either trying out [`speedtest-cli`](https://github.com/sivel/speedtest-cli) or forking this project.
