### ISSUE TITLE
Have you seen analogue before?

### ISSUE THREAD

**Issue by nkt** [sindresorhus/speed-test#5]
https://github.com/sivel/speedtest-cli
It's written using python, so you can run it's everywhere.
On OSX just run `brew install speedtest_cli`.

**Comment by sindresorhus** [comment]
Yup, saw it after I made this. Wouldn't have mattered though. The output of `speedtest-cli` is pretty messy and it has way too many options and bugs. I also think this one is much more user-friendly.
