### ISSUE TITLE
Verbose mode

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/speed-test#6]
Would be useful to have a `--verbose` flag that displays more info, like which server it connects to, etc.

What would you like to have included in the verbose output?

Available info can be found here: https://github.com/ddsol/speedtest.net#data

**Comment by KoalaBear84** [comment]
- Chosen server
- Location+Country and Distance to server

And also min/max pings and speeds. Maybe also if not verbose, depends on how much data it is and if it is cluttering too much, then not.

**Comment by SamVerschueren** [comment]
This is quite easy to implement, but my main concern is how to show the information without cluttering the view :p. Any design ideas @sindresorhus ?

**Comment by sindresorhus** [comment]
@SamVerschueren I was thinking just showing it in the list:

```
      Ping
  Download   
    Upload   
    Server
  Location
  Distance
       Etc
```

And should also be included in the `--json` output.

**Comment by SamVerschueren** [comment]
Should we add an empty line between the verbose properties and the normal properties to make a clear distinction? The main reason someone is running a speed-test is because they want the speed of there connection, right?

```
      Ping
  Download   
    Upload   

    Server
  Location
  Distance
       Etc
```

**Comment by sindresorhus** [comment]
Sure

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/speed-test/pull/21.
