### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by wenisonbp** [sindresorhus/speed-test#64]
Hello, please, can you help me with this error? I need to know if this library can be used on production servers. I'm using a library on a Windows production server and I want to capture the client's speed test, but this error is occurring:

Error: connect ECONNREFUSED 179.109.32.34:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
Emitted 'error' event at: {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '179.109.32.34',
  port: 8080
}

**Comment by sindresorhus** [comment]
This is meant to test your own internet speed, not as a server to test others.
