### ISSUE TITLE
Show current download speed during the test

### ISSUE THREAD

**Issue by ai** [sindresorhus/speed-test#7]
In SpeedTest site I can understand average download speed even before test is finished, because it shows current download speed. It is not accurate, but enough in many cases.

**Comment by sindresorhus** [comment]
Yeah, that would be nice. This needs to be exposed by the underlaying lib used by this module though. Can you open a ticket on https://github.com/ddsol/speedtest.net/issues? Will keep this one open for anyone else looking for this.

**Comment by ai** [comment]
Done https://github.com/ddsol/speedtest.net/issues/9

**Comment by Whoaa512** [comment]
Exposed ddsol/speedtest.net#10

**Comment by ai** [comment]
@sindresorhus API is added, wait for release

**Comment by sindresorhus** [comment]
It's out, but I haven't had the time to add it yet. Happy to receive a pull request. Otherwise I'll add it when I get some free time.
